# See http://jekyllrb.com/docs/github-pages/ for more info
baseurl: 		'/DragonSlayersJr'
baseurlremote:  '/DragonSlayersJr'
assetsurl:      'assets/'

# Google Analytics
ga:
  root: 'himedlooff.github.io'
  id: 'UA-46323278-1'
  